source_dir: /usr/share/icons/oxygen
destination_dir: public/images/models

resource_sizes: [ 16, 48, 64, 128 ]

mime_types:
  - application-pdf.png
  - application-postscript.png
  - application-rtf.png
  - application-vnd.ms-excel.png
  - application-vnd.ms-powerpoint.png
  - application-vnd.oasis.opendocument.presentation.png
  - application-vnd.oasis.opendocument.spreadsheet.png
  - application-vnd.oasis.opendocument.text.png
  - application-vnd.scribus.png
  - audio-x-wav.png
  - text-html.png

# size is resource_sizes by default
resources:
  - dir: mimetypes
    file: application-msword.png
    name: application-vnd.ms-word.png
  - dir: mimetypes
    file: audio-x-generic.png
    name: audio-mpeg.png
  - dir: mimetypes
    file: audio-x-generic.png
    name: audio-x-vorbis-ogg.png
  - dir: apps
    file: gimp.png
    name: image-x-xcf.png
  - dir: actions
    file: view-media-artist.png
    name: anonymous.png
    size: [ 16 ]
  - dir: apps
    file: kalarm.png
    name: cron_agent.png
    size: [ 16 ]
 
# size is 16 by default
new_resources:
  - dir: actions
    file: archive-insert.png
    name: document
  - dir: actions
    file: document-edit.png
    name: article
  - dir: actions
    file: insert-link.png
    name: bookmark
  - dir: actions
    file: appointment-new.png
    name: task
  - dir: actions
    file: user-group-new.png
    name: group
    size: [ 32, 48 ]
    
